services:
  dingo:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - vendor:/app/vendor
    container_name: dingo
    networks:
      - dingo
  
  webserver:
    build: nginx
    ports:
      - "8080:80"
    container_name: webserver
    depends_on:
      - dingo
    volumes:
      - ./:/var/www/html
    networks:
      - dingo

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dingo
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dingo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql_db
    networks:
      - dingo

networks:
  dingo:
    external: true

volumes:
  mysql_data:
  vendor:
